site_name: Squarehuang's  DejaVu
site_url: https://squarehuang.cn
repo_url: https://github.com/SeeleVolle/SeeleVolle.github.io
repo_name: SeeleVolle/SeeleVolle.github.io
edit_uri: https://github.com/SeeleVolle/SeeleVolle.github.io/tree/main/docs/
site_description: Squarehuang的博客
site_author: Squarehuang

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue grey
      accent: light blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: blue grey
      accent: light blue
  language: zh

  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    # 页面编辑
    - content.action.edit
    # 底部导航
    - navigation.footer
    # 顶部导航
    - navigation.tabs
    # 返回顶部
    - navigation.top
    # 点击标签回到首页
    - navigation.tracking
    - navigation.indexes
    # 搜索
    - search.suggest
    - search.highlight
    - search.share

  #custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
    admonition:
      info: fontawesome/solid/anchor
      note: fontawesome/solid/pen-nib
      abstract: fontawesome/solid/list
      tip: fontawesome/solid/lightbulb
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: material/alien
      danger: fontawesome/solid/virus
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/link
      
extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  social:
  - icon: fontawesome/solid/paper-plane
    link: mailto:<jjhuang5@outlook.com>
    name: 邮箱地址
copyright: Copyright &copy; 2021 - 2024 squarehuang.cn
extra_css:
    - stylesheets/extra.css
extra_javascript:
    - javascripts/extra.js
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  # Admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - tables
  - footnotes
  # Grid, Image
  - attr_list
  - md_in_html
  # Icon
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg 
  # List
  - def_list
  - pymdownx.snippets
  # Code Block
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  #MathJax
  - pymdownx.arithmatex:
        generic: true
  #Keys
  - pymdownx.keys:
      separator: +
      strict: false
      camel_case: false
  #Toc
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - git-revision-date-localized:
      type: datetime
      #fallback_to_build_date: true
      enable_creation_date: false
  - blog:
      blog_dir: blog
      post_date_format: medium
      post_url_format: "{slug}"
      post_excerpt: required
      post_excerpt_separator: <!-- more -->
      post_excerpt_max_categories: 2
      post_excerpt_max_authors: 2
      archive_name: Squarehuang's 归档
      archive_url_format: "archive/{date}"
      archive_url_date_format: yyyy
      categories_name: Squarehuang's 分类
      categories_url_format: "category/{slug}"
      authors_file: "{blog}/.authors.yml"
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      pagination_per_page: 5
      draft: true
      draft_if_future_date: true  
  - git-authors:
      enabled: 
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: auto
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
  - search
      
nav:
  - "简介":
    - "简介": index.md
  - "课程笔记":
    - course/index.md
    - course/cs231n.md
    - course/大数据存储与计算技术.md
  - "论文阅读":
    - paper/index.md
    - paper/Transformer_Review.md
    - paper/Wanda.md
    - paper/SparseGPT.md
    - paper/PowerInfer.md
    - paper/SHEARED LLama.md
    - paper/DejaVu.md
    - paper/Atom.md
    - paper/GEAR.md
    - paper/PIM_DL.md
    - paper/LUT-NN.md
    - paper/DistServe.md
    - paper/FastDecode.md
    - paper/DEFT.md
    - paper/Mooncake.md
#Review part
#    - papet/Preble.md
#    - paper/SpGETT.md
  - 技术积累:
    - tech/index.md
    - "常用工具":
      - tech/tools/Mysql.md
      - tech/tools/Docker.md
      - tech/tools/ssh.md
      - tech/tools/nfs.md
      - tech/tools/Git.md
      - tech/tools/CondaPipNotes.md
    - "编程语言 | 范式 | Linux":
      - tech/coding/GoF23 Notes.md
      - tech/coding/modernC++.md
      - tech/coding/CUDA.md
      - tech/coding/PIM.md
      - tech/coding/Linux.md
    - "Machine Learning":
      - tech/ml/Linear Algebra.md
      - tech/ml/MachineLearning.md
    - "其他知识":
      - tech/others/odd.md
      - tech/others/sparsematrix.md
  - 个人闲谈:
    - blog/index.md
  - 无用收藏:
    - 网页总览: favorites/index.md
    - Markdown语法: favorites/markdown.md
