name: gh-deploys

env:
  TZ: Asia/Shanghai

on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          fetch-depth: 0
      - run: pip install mkdocs-material
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-git-authors-plugin 
      - run: pip install mkdocs-glightbox
      - run: pip install mdx-truly-sane-lists
      - run: mkdocs gh-deploy --force
  